dist: trusty
sudo: required
language: python

python:
  - 3.5

env:
  - TEXNOPROM_DB_LOGIN="postgres" TEXNOPROM_DB_PASSWORD="" TEXNOPROM_DB_HOST="127.0.0.1"

services:
  - postgresql

install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database olympic_games;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
